# Generated by Django 4.2.11 on 2024-05-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('status', models.TextField(choices=[(0, 'Провалено'), (1, 'Не принят'), (2, 'В работе'), (3, 'Выполнено')])),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
